/**
 * Unit tests for lib/export-md.ts — Markdown report export
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("@/lib/settings", () => ({
  getSettings: vi.fn(() => ({
    app: { name: "AMLClaw", reportHeader: "", themeDefault: "dark" },
  })),
}));

import { generateExportMd } from "@/lib/export-md";
import { getSettings } from "@/lib/settings";

const mockGetSettings = vi.mocked(getSettings);

beforeEach(() => {
  vi.resetAllMocks();
  mockGetSettings.mockReturnValue({
    app: { name: "AMLClaw", reportHeader: "", themeDefault: "dark" },
  } as any);
});

describe("export-md", () => {
  const baseJob = {
    completed_at: "2025-01-01T00:00:00Z",
    request: { chain: "Ethereum", address: "0xabc", scenario: "deposit", ruleset: "singapore_mas" },
    result: {
      target: { chain: "Ethereum", address: "0xabc", tags: [], self_matched_rules: [] },
      scenario: "deposit",
      summary: { highest_severity: "Low", rules_triggered: [], total_rules: 10 },
      risk_entities: [],
    },
  };

  it("generates a valid markdown report", () => {
    const md = generateExportMd(baseJob);
    expect(md).toContain("# AML Address Screening Report");
    expect(md).toContain("0xabc");
    expect(md).toContain("Ethereum");
    expect(md).toContain("deposit");
    expect(md).toContain("Generated by AMLClaw Web");
  });

  it("includes report header when configured", () => {
    mockGetSettings.mockReturnValue({
      app: { name: "TestCo", reportHeader: "CONFIDENTIAL REPORT", themeDefault: "dark" },
    } as any);
    const md = generateExportMd(baseJob);
    expect(md).toContain("CONFIDENTIAL REPORT");
    expect(md).toContain("---");
  });

  it("shows clean result when no risk entities", () => {
    const md = generateExportMd(baseJob);
    expect(md).toContain("No risk entities detected");
    expect(md).toContain("Pass");
  });

  it("shows risk entities with details", () => {
    const job = {
      ...baseJob,
      result: {
        ...baseJob.result,
        summary: {
          highest_severity: "High",
          rules_triggered: ["R001"],
          total_rules: 10,
        },
        risk_entities: [
          {
            address: "0xevil",
            tag: { primary_category: "Sanctions", risk_level: "High" },
            min_deep: 2,
            matched_rules: ["R001"],
            evidence_paths: [{ deep: 2, flow: "0xabc -> 0xmid -> 0xevil" }],
          },
        ],
      },
    };
    const md = generateExportMd(job);
    expect(md).toContain("0xevil");
    expect(md).toContain("Sanctions");
    expect(md).toContain("R001");
    expect(md).toContain("Reject");
  });

  it("shows self-risk assessment when target has tags", () => {
    const job = {
      ...baseJob,
      result: {
        ...baseJob.result,
        target: {
          ...baseJob.result.target,
          tags: [{ primary_category: "Gambling", secondary_category: "Online", risk_level: "Medium" }],
          self_matched_rules: ["SELF_R1"],
        },
      },
    };
    const md = generateExportMd(job);
    expect(md).toContain("Target Self-Risk Assessment");
    expect(md).toContain("Gambling");
    expect(md).toContain("SELF_R1");
  });

  it("handles empty/minimal job gracefully", () => {
    const md = generateExportMd({});
    expect(md).toContain("# AML Address Screening Report");
    expect(md).toContain("No risk entities detected");
  });
});
